// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg8sAF1fvtwSBQ1ad7fos_REEjTAAvDzg',
    appId: '1:126223909088:web:3e95bcf74b1553668d9085',
    messagingSenderId: '126223909088',
    projectId: 'foodpanda-42a3a',
    authDomain: 'foodpanda-42a3a.firebaseapp.com',
    storageBucket: 'foodpanda-42a3a.firebasestorage.app',
    measurementId: 'G-CQMHDBV0SC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJbunTkct8T-NTesKsoF9aWULzUcqxJBs',
    appId: '1:126223909088:android:f068a06312a416b68d9085',
    messagingSenderId: '126223909088',
    projectId: 'foodpanda-42a3a',
    storageBucket: 'foodpanda-42a3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOeRuCk4wjxScYSWjWwrlViGNCDqkIDbU',
    appId: '1:126223909088:ios:f71f6e06f46b508c8d9085',
    messagingSenderId: '126223909088',
    projectId: 'foodpanda-42a3a',
    storageBucket: 'foodpanda-42a3a.firebasestorage.app',
    iosBundleId: 'com.example.laoFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOeRuCk4wjxScYSWjWwrlViGNCDqkIDbU',
    appId: '1:126223909088:ios:f71f6e06f46b508c8d9085',
    messagingSenderId: '126223909088',
    projectId: 'foodpanda-42a3a',
    storageBucket: 'foodpanda-42a3a.firebasestorage.app',
    iosBundleId: 'com.example.laoFood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg8sAF1fvtwSBQ1ad7fos_REEjTAAvDzg',
    appId: '1:126223909088:web:51fd4150fb7c4b3d8d9085',
    messagingSenderId: '126223909088',
    projectId: 'foodpanda-42a3a',
    authDomain: 'foodpanda-42a3a.firebaseapp.com',
    storageBucket: 'foodpanda-42a3a.firebasestorage.app',
    measurementId: 'G-YSB7EQ88YZ',
  );
}
